steps:
  # เชื่อมต่อกับ GKE Cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'autopilot-strapi'
      - '--region'
      - '--project'
      - 'cloud-project-448820'

  # Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/cloud-project-448820/strapi:latest'
      - '.'

  # Push Docker Image ไปยัง GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/cloud-project-448820/strapi:latest'

  # ลบ Deployment เก่า
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'kubectl'
      - 'delete'
      - 'deployment'
      - 'strapi-deploy'
      - '-n'
      - 'strapi'

  # สร้าง Deployment ใหม่
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'kubectl'
      - 'apply'
      - '-f'
      - 'deployment.yaml'

  # ตรวจสอบสถานะ Deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'kubectl'
      - 'rollout'
      - 'status'
      - 'deployment/strapi-deploy'
      - '-n'
      - 'strapi'
      
options:
  logging: "NONE"
