steps:
  # Connect to GKE Cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'autopilot-strapi'
      - '--region'
      - 'asia-southeast1'
      - '--project'
      - 'cloud-project-448820'

  # Delete old Deployment (if fails, continue)
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'delete'
      - 'deployment'
      - 'strapi-deploy'
      - '-n'
      - 'strapi'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-strapi'
    allowFailure: true  # If this step fails, continue to the next step

  # Build Docker Image with no cache
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'gcr.io/cloud-project-448820/strapi:latest'
      - '.'

  # Push Docker Image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/cloud-project-448820/strapi:latest'

  # set Docker Image to k8s
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/strapi-deploy'
      - 'strapi=gcr.io/cloud-project-448820/strapi:latest'
      - '-n'
      - 'strapi'

  # Create new Deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-strapi'

  # Check Deployment status
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/strapi-deploy'
      - '-n'
      - 'strapi'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-strapi'
      
  # Update the service to use the correct selector
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'patch'
      - 'service'
      - 'strapi-deploy-service'
      - '-n'
      - 'strapi'
      - '--type'
      - 'json'
      - '-p'
      - '[{"op": "replace", "path": "/spec/selector", "value": {"app": "strapi"}}]'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-strapi'

options:
  logging: "NONE"
