steps:
  # เชื่อมต่อกับ GKE Cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'autopilot-strapi'
      - '--region'
      - 'asia-southeast1'
      - '--project'
      - 'cloud-project-448820'

  # Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/cloud-project-448820/strapi:latest'
      - '.'

  # Push Docker Image ไปยัง GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/cloud-project-448820/strapi:latest'

  # ลบ Deployment เก่า
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'delete'
      - 'deployment'
      - 'strapi-deploy'
      - '-n'
      - 'strapi'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-strapi'

  # สร้าง Deployment ใหม่
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-strapi'

  # ตรวจสอบสถานะ Deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/strapi-deploy'
      - '-n'
      - 'strapi'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-strapi'

options:
  logging: "NONE"
