steps:
  # ใช้คำสั่ง gcloud เพื่อทำการเชื่อมต่อกับ GKE Cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'autopilot-strapi'
      - '--region=asia-southeast1'

  # ใช้ kubectl เพื่อเชื่อมต่อกับ GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'config'
      - 'use-context'
      - 'gke_cloud-project-448820_asia-southeast1_autopilot-strapi'
    id: "Set kubectl context"


  # Deploy ขึ้น Kubernetes โดยใช้ไฟล์ deployment.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'deploy'
      - 'apply'
      - '--file'
      - 'deployment.yaml'
      
options:
  logging: "NONE"
