steps:
  # เชื่อมต่อกับ GKE Cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'autopilot-strapi'
      - '--region'
      - 'asia-southeast1'
      - '--project'
      - 'cloud-project-448820'

  # ลบ Deployment เก่า
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'delete-deployment'
      - 'strapi-deploy'
      - '--namespace'
      - 'strapi'

  # สร้าง Deployment ใหม่
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'apply'
      - '-f'
      - 'deployment.yaml'

  # ตรวจสอบสถานะ Deployment
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'rollout'
      - 'status'
      - 'deployment/strapi-deploy'
      - '--namespace'
      - 'strapi'
      
options:
  logging: "NONE"
