steps:
  # เชื่อมต่อกับ GKE Cluster
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - 'autopilot-strapi'
      - '--region=asia-southeast1'
      - '--project=cloud-project-448820'

  # อัปเดต Image ใน Deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/strapi-deploy'
      - 'strapi=gcr.io/cloud-project-448820/strapi:latest'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-strapi'

  # ตรวจสอบสถานะการอัปเดต Deployment
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'rollout'
      - 'status'
      - 'deployment/strapi-deploy'
      - '-n'
      - 'strapi'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-southeast1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=autopilot-strapi'
