apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-deploy
  namespace: strapi
  labels:
    app: strapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
      - name: strapi
        image: gcr.io/cloud-project-448820/strapi:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: strapi-env  # ชื่อ Secret ที่ต้องการใช้
        ports:
        - containerPort: 80
        resources:
          limits:
            ephemeral-storage: 1Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
