steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/cloud-project-448820/strapi-image', '-f', '.devops/Dockerfile', '.' ]
images:
- 'gcr.io/cloud-project-448820/strapi-image'